name: Publish Docker
on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04 # temp change until they deploy a fix by 10/18/2019
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nopjmp/lucoabot
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
