name: Publish Docker
on: [push]

# TODO: buildkit once Docker is updated on the workers
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Building Docker Image
        env:
          CONTAINER_IMAGE_NAME: ${{ secrets.CONTAINER_IMAGE_NAME }}
        run: docker build --no-cache -t $CONTAINER_IMAGE_NAME:latest .
      - name: Push Docker Image to Registry
        env:
          CONTAINER_IMAGE_NAME: ${{ secrets.CONTAINER_IMAGE_NAME }}
        run: docker push $CONTAINER_IMAGE_NAME:latest
